guard :minitest do
  # with Minitest::Spec
  watch(%r{^spec/(.*)_spec\.rb$})
  watch(%r{^lib/(.+)\.rb$})         { |m| "spec/#{m[1]}_spec.rb" }
  watch(%r{^spec/spec_helper\.rb$}) { 'spec' }
end

# require 'minitest/autorun'
# require 'minitest/reporters'
#
# Minitest::Reporters.use! Minitest::Reporters::SpecReporter.new
#
#
# require_relative '../lib/customer'
# require_relative '../lib/order'
